#' Download with diagnostics
#'
#' @param url link generated by the code?
#'
#' @param file object containing data?
#'
#' @param destdir character value indicating the directory
#' in which to store downloaded files.
#'
#'
#' @export
dod.download <- function(url, file, destdir)
{
    message(file)
    fullfile <- paste0(destdir, "/", file)
    message(fullfile)
    t <- try(download.file(url, fullfile), silent=TRUE);
    if (inherits(t,"try-error")) {
        stop("fix me later")
    }
    file
}
